### ISSUE TITLE
How can I use the original 3DGS viewer to view the trained generated model?

### ISSUE THREAD

**Issue by GimV88** [maincold2/Compact-3DGS#11]
How can I use the original 3DGS viewer to view the trained generated model?I really need your help, please advise

**Comment by maincold2** [comment]
Please refer to the readme:

The original SIBR interactive viewer of 3DGS can not support neural fields for view-dependent color. We would like to support and update this shortly if possible.

Currently, to use the viewer, you have two options: either bypass the neural field for view-dependent color by only applying masking and the geometry codebook, or train neural fields to represent spherical harmonics without inputting view direction (slightly lower performance). After this, you can save the output in a PLY format, similar to 3DGS.

Thanks!

**Comment by GimV88** [comment]
So, may I ask how the visualization images and comparisons of the training results mentioned in the paper were obtained?
![Snipaste_2024-02-22_20-29-54](https://github.com/maincold2/Compact-3DGS/assets/139735915/16e4193f-9ccd-411f-9edc-4ff3aa0381b7)

**Comment by maincold2** [comment]
Sure, the 3 center images were obtained by applying only the masking strategy, reflecting our core idea.
The right-most image was rendered with other attribute compaction including I-NGP and post-processings.
