### ISSUE TITLE
Question about the storage size of scale and rotation

### ISSUE THREAD

**Issue by mush-room** [maincold2/Compact-3DGS#13]
Dear authors,

Thanks for your amazing work!
I have a question about the storage size of scale and rotation. I notice that the storage size of each module is listed in the **storage** file. When I read the source code (line 469-470 in _gaussian_render.py_),

> `scale_mb = self._xyz.shape[0]*self.rvq_bit*self.rvq_num/8/10**6`
> `rotation_mb = self._xyz.shape[0]*self.rvq_bit*self.rvq_num/8/10**6`

it seems that only the storage size of the indices is calculated and the size of the codebook is ignored.
Did I miss something or is there something wrong with my understanding? Looking forward to your reply.

**Comment by maincold2** [comment]
Yeah, you are right!
However, we ignored the codebook size that requires only 0.005 MB and 0.006 MB for scale and rotation, respectively, in our case.
e.g.) 2^6 (codes) * 6 (#stages) * 3 (scale vector length) * 32bit

To ensure the generality, we would update the code accordingly.
Thank you!

**Comment by mush-room** [comment]
Thank you very much for your prompt reply, which resolved my problem well!

**Comment by maincold2** [comment]
It has been updated now! dc5240235e61435d0c3116a52ee12932cd65652b

**Comment by mush-room** [comment]
I see it! Thanks again for your efforts!😄
