### ISSUE TITLE
Viewing trained results

### ISSUE THREAD

**Issue by alexhjkim** [maincold2/Compact-3DGS#14]
Hello, thank you for your great work!

I read the README about the original SIBR interactive viewer of 3DGS not being able to support neural fields for view-dependent color. May I ask how you viewed the results of Compact-3DGS without using the viewer, and how you generated the videos of the results, as can be seen on the [project page](https://maincold2.github.io/c3dgs/)?

**Comment by maincold2** [comment]
Now we have updated the code for rendering videos, which is originally from [LightGaussians](https://github.com/VITA-Group/LightGaussian/).

```shell
python render_video.py --source_path PATH/TO/DATASET --model_path PATH/TO/MODEL --skip_train --skip_test --video
```

We used trained models without neural fields for the visualization of ellipsoids in the paper (to visualize the effect of masking), and other rendered results were with neural fields by using the python scripts.

Thanks!

**Comment by alexhjkim** [comment]
Thanks for the update!
