### ISSUE TITLE
Dataset for training problem

### ISSUE THREAD

**Issue by Dreambyland** [maincold2/Compact-3DGS#15]
I'm facing problem with training . I downloaded a couple datesets : 360_extra_scenes, nerf_synthetic ,person-hall (colmap dataset).
while running command:  python train.py -s /home/dream/Compact-3DGS/person-hall --eval
terminall error shows: Optimizing 
Output folder: ./output/639f2394-f [21/03 15:00:38]
Tensorboard not available: not logging progress [21/03 15:00:38]
Traceback (most recent call last):
  File "/home/dream/Compact-3DGS/scene/dataset_readers.py", line 136, in readColmapSceneInfo
    cam_extrinsics = read_extrinsics_binary(cameras_extrinsic_file)
  File "/home/dream/Compact-3DGS/scene/colmap_loader.py", line 187, in read_extrinsics_binary
    with open(path_to_model_file, "rb") as fid:
****FileNotFoundError: [Errno 2] No such file or directory: '/home/dream/Compact-3DGS/person-hall/sparse/0/images.bin'****

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 233, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.comp)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/dream/Compact-3DGS/scene/__init__.py", line 45, in __init__
    scene_info = sceneLoadTypeCallbacks["Colmap"](args.source_path, args.images, args.eval)
  File "/home/dream/Compact-3DGS/scene/dataset_readers.py", line 142, in readColmapSceneInfo
    cam_intrinsics = read_intrinsics_text(cameras_intrinsic_file)
  File "/home/dream/Compact-3DGS/scene/colmap_loader.py", line 171, in read_intrinsics_text
    assert model == "PINHOLE", "While the loader support other types, the rest of the code assumes PINHOLE"
AssertionError: While the loader support other types, the rest of the code assumes PINHOLE

Did you face this kind of error? 

In that dataset there is no file with: images.bin.

Can you provide the link for dataset what you have been used? 

Also error for nerf_sytnthetic dataset: 
(c3dgs) dream@dream:~/Compact-3DGS$ python train.py -s /home/dream/Compact-3DGS/nerf_synthetic --eval --max_hashmap 16 --lambda_mask 4e-3 --mask_lr 1e-3 --net_lr 1e-3 --net_lr_step 25000
Optimizing 
Output folder: ./output/cf5141b6-1 [21/03 15:18:53]
Tensorboard not available: not logging progress [21/03 15:18:53]
Traceback (most recent call last):
  File "train.py", line 233, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.comp)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "/home/dream/Compact-3DGS/scene/__init__.py", line 50, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

**Comment by maincold2** [comment]
You would have to pass each scene folder path:

python train.py -s /home/dream/Compact-3DGS/nerf_synthetic/**lego** --eval --max_hashmap 16 --lambda_mask 4e-3 --mask_lr 1e-3 --net_lr 1e-3 --net_lr_step 25000


I have not used the person-hall dataset, so it would be helpful to refer https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#processing-your-own-scenes.

Thanks.

**Comment by Dreambyland** [comment]
Than

> You would have to pass each scene folder path:
> 
> python train.py -s /home/dream/Compact-3DGS/nerf_synthetic/**lego** --eval --max_hashmap 16 --lambda_mask 4e-3 --mask_lr 1e-3 --net_lr 1e-3 --net_lr_step 25000
> 
> I have not used the person-hall dataset, so it would be helpful to refer https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#processing-your-own-scenes.
> 
> Thanks.

Thank you for replying. But i have still facing problem with nerf_synthetic. Traceback (most recent call last):
  File "train.py", line 233, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.comp)
  File "train.py", line 35, in training
    scene = chair(dataset, gaussians)
NameError: name 'chair' is not defined
Are we suppose to debug the code or properly set the dataset folder? Lego scene locates : Compact-3DGS/nerf_synthetic/nerf_synthetic. 

 Thank you again

**Comment by maincold2** [comment]
Why did you modify the function (Scene) name to chair here?: scene = chair(dataset, gaussian)

You would have to pass the scene folder (after -s) like 'Compact-3DGS/nerf_synthetic/nerf_synthetic/ego' or 'Compact-3DGS/nerf_synthetic/nerf_synthetic/chair'.

**Comment by Dreambyland** [comment]
> Why did you modify the function (Scene) name to chair here?: scene = chair(dataset, gaussian)
> 
> You would have to pass the scene folder (after -s) like 'Compact-3DGS/nerf_synthetic/nerf_synthetic/ego' or 'Compact-3DGS/nerf_synthetic/nerf_synthetic/chair'.

there are other scene,therefore i wanted check other scene too,that's why put chair.

**Comment by maincold2** [comment]
As just passing the proper scene folder path with -s automatically configures each scene, you should get back the code.

**Comment by Dreambyland** [comment]
Thank you!

**Comment by xdu-Liu-learn** [comment]
作者，您好1
Submethod,PSNR,SSIM,LPIPS,Size [Bytes],#Gaussians
 w/o PP,29.2641716,0.9000701,0.2578339,47979841,1339005
 w/ PP,29.1633472 ,0.8993502 ,0.2573153 ,25739989,1339005
生成这个结果是根据每个数据集的不同场景评估结果，进行平均计算得到的吗？
