### ISSUE TITLE
 How to proceed without post-processing techniques?

### ISSUE THREAD

**Issue by GimV88** [maincold2/Compact-3DGS#16]
Hello,

I am interested in using your algorithm to train a model without post-processing techniques.Could you please provide guidance on how to proceed with this?
I appreciate your assistance in this matter. Thank you.

**Comment by maincold2** [comment]
You can run the training script without --comp option (https://github.com/maincold2/Compact-3DGS?tab=readme-ov-file#--comp).
Thanks.

**Comment by GimV88** [comment]
Thanks!

**Comment by GimV88** [comment]
Why do I get the same training results when I use the command as shown in the figure (with --comp) as when I don't use it?
![image](https://github.com/maincold2/Compact-3DGS/assets/139735915/dcf33242-19a3-4f79-a8bc-e0758ce44313)
