### ISSUE TITLE
Regarding the issue of storage size.

### ISSUE THREAD

**Issue by whwh747** [maincold2/Compact-3DGS#17]
Hello, thank you very much for your excellent work. I am a novice, and I would like to understand the issue of how to calculate storage size. After training, is the size of the point_cloud.ply file the result of the storage(MB) reported in the paper? I look forward to your reply.

**Comment by maincold2** [comment]
The storage of the ply file, where every parameter is stored with 32float container, does not reflect the actual storage.
We calculate the actual storage requirements in the 'storage' file: each stored format is described in Table 5 in the recent arxiv paper.
Also, it would be helpful to refer to https://github.com/maincold2/Compact-3DGS/issues/10#issuecomment-1946334891.

**Comment by whwh747** [comment]
Thank you for your response, but I still didn't understand what you meant. Are you saying that the actual storage is not the size of the point_cloud.ply file in the outputs folder? Then how is the actual storage calculated? The recent arXiv paper you mentioned, which one are you specifically referring to? I hope to receive your reply!

**Comment by maincold2** [comment]
We now update the code to save the result file reflecting the actual storage.
Please refer to the updated readme (https://github.com/maincold2/Compact-3DGS/tree/main?tab=readme-ov-file#442024).
Also, please check here for how to calculate the storage:
https://github.com/maincold2/Compact-3DGS/blob/50b48b0afe0205a834d479e3a0511068200d4409/scene/gaussian_model.py#L556
