### ISSUE TITLE
Question about learning the mask of opacity

### ISSUE THREAD

**Issue by JIANG-CX** [maincold2/Compact-3DGS#22]
Wonderful work!
I understand that some Gaussians with a small scale cannot be removed, so we should learn a mask to exclude them. However, I'm puzzled as to why an opacity mask is necessary, given that Gaussians with low opacity could be eliminated through the original pruning process.

**Comment by maincold2** [comment]
Yeah, actually masking opacity could play a similar role to the original pruning.
But we can prune more Gaussians by learning based on gradients from rendering loss, considering both opacities and scales.

**Comment by JIANG-CX** [comment]
Ok, thanks for your reply.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Joo Chan Lee ***@***.***>
发送时间: Monday, July 22, 2024 1:17:39 PM
收件人: maincold2/Compact-3DGS ***@***.***>
抄送: JIANG Chenxing ***@***.***>; Author ***@***.***>
主题: Re: [maincold2/Compact-3DGS] Question about learning the mask of opacity (Issue #22)


Yeah, actually masking opacity could play a similar role to the original pruning.
But we can prune more Gaussians by learning based on gradients from rendering loss, considering both opacities and scales.

―
