### ISSUE TITLE
How to visualize result ply file?

### ISSUE THREAD

**Issue by TxT1212** [maincold2/Compact-3DGS#5]
Thanks for your amazing work! Could you suggest a preferred method for visualization? I was using this [web](https://antimatter15.com/splat/) to visualize origin gs results, but it can't load yours.

**Comment by TxT1212** [comment]
I use modification in https://github.com/maincold2/Compact-3DGS/issues/1#issue-2013692427 
and able to use previous method to visualize.

**Comment by TxT1212** [comment]
With https://github.com/maincold2/Compact-3DGS/issues/1#issue-2013692427 point cloud can be visualized, but the colors are off, seeming like some boundary-less random color blocks.

**Comment by maincold2** [comment]
Please refer to #1 and the updated readme.
