### ISSUE TITLE
Question for eq 1

### ISSUE THREAD

**Issue by SYSUykLin** [maincold2/Compact-3DGS#8]
I saw the eq 1 have a stop gradient symbol, where is the code? I did not find stop gradient in the code. 
Thanks

**Comment by maincold2** [comment]
You can refer to gaussian_renderer/__init__.py.
https://github.com/maincold2/Compact-3DGS/blob/a46a15ea8c600d8a24412871bae6da816dcb406e/gaussian_renderer/__init__.py#L68

Thanks!
