### ISSUE TITLE
Questions about RVQ

### ISSUE THREAD

**Issue by asher-bit** [maincold2/Compact-3DGS#9]
The general codebook operation is to store codebooks and indexes. But in your code, it seems that only the quantized scale and rotation are stored in the final stage. what is the reason for this?

**Comment by maincold2** [comment]
As described in Section 6 in Appendix, quantized attributes do not need to be indiced at every rendering iteration but just obtained once before rendering.
So, we apply VQ at the end of training and store like 3DGS for a simpler implementation, while we assume to store codebooks/indices and calculate the storage of them.

Thank you!

**Comment by asher-bit** [comment]
Thank you very much for your prompt reply!
